import { Inter } from 'next/font/google'
import './globals.scss';
import Header from '../components/Header/Header';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { montserrat } from '../font';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <main className={montserrat.className}>
          {children}
        </main>
      </body>
    </html>
  )
}
